id: P009414
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG1247
  title: འཇིགས་བྱེད་ཆོས་འབྱུང
  author: ''
  volumes:
    d8090b2d38ff4895a9fdc7a1bfe13a90:
      image_group_id: I1KG1261
      title: ''
      volume_number: 1
      total_pages: 812
      base_file: v001.txt
